Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,7 +22,11 @@ jobs:
       - name: Read application file
         run: cat app.txt
       - name: Failure altert
-        run: exit 1
+        run: |
+          if [ ! -f app.conf ]; then
+           echo "File missing"
+           exit 1
+          fi
       - name: Runs only in main branch
         if: github.ref == 'ref/heads/main'
         run: echo "Runing in main branch"
